### ISSUE TITLE
“Response status code does not indicate success: 400 (Bad Request).”

### ISSUE THREAD

**Issue by Mohitaban** [microsoft/powerbi-azure-pipelines-extensions#12]
While adding a user to workspace in power BI using "Add a user to workspace" task I am getting an error “Response status code does not indicate success: 400 (Bad Request).” Can anyone please tell me how to resolve it.

**Comment by MahirDiab** [comment]
Hi @Mohitaban , sorry for the delay - 400 bad request, is a general error and doesn't indicate the exact issue.
with the new version (1.1.0) just released you should be able to see the error code which should explain the issue
please re-try this and provide the updated log if additional help is needed
