### ISSUE TITLE
Power BI Automation (tools): "This extension is not installable on any currently installed products." 

### ISSUE THREAD

**Issue by mmccarthy19** [microsoft/powerbi-azure-pipelines-extensions#13]
The download is not working. We believe we have the necessary installations (Report Builder, Desktop). Is there something else we need installed before this download to be able to use the extension?
[dd_VSIXInstaller_20220616145303_46f0.log](https://github.com/microsoft/powerbi-azure-pipelines-extensions/files/8928740/dd_VSIXInstaller_20220616145303_46f0.log)

Thanks,
Mike Mc

**Comment by MahirDiab** [comment]
Hi @mmccarthy19, seems like you are trying to install this on your computer
this extension is for Azure DevOps to provide custom tasks to be run on Azure DevOps Pipelines / releases.
