### ISSUE TITLE
Deploy content to the Test stage : Error 400

### ISSUE THREAD

**Issue by Cha74** [microsoft/powerbi-azure-pipelines-extensions#14]
Hello, 

When I try to deploy, I get a 400 error every time. 

I have tried different names for the new workspace though. 

But nothing works 

![image](https://user-images.githubusercontent.com/99191094/181524293-def1f229-1129-4200-a97f-ed5b99edae61.png)

**Comment by kohithms** [comment]
@Cha74  check whether the App registration has valid permissions shared in public doc.

**Comment by Cha74** [comment]
@kohithms 

The weird thing is that sometimes it works and sometimes it doesn't  

But I'll check it out thanks !

**Comment by jontreynes** [comment]
@Cha74 and @kohithms - I'm receiving the same error. As per the public doc it only states 
_Pipeline.Deploy_ and _The user must at least be a member on both source and target deployment workspaces_

My app registration has these permissions already. I've also made sure to _Allow service principals to use Power BI APIs_ as it states here 
https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal#step-3---enable-the-power-bi-service-admin-settings. I've included my app registration as an admin on the pipeline as well

I'm not sure what else is missing.

**Comment by jontreynes** [comment]
Update: My issue was resolved when setting updateAppSettings to false. In my case, it was suppose to be false because I had no powerbi app

**Comment by MahirDiab** [comment]
Hi, sorry for the delay - 400 bad request, is a general error and doesn't indicate the exact issue.
with the new version (1.1.0) just released you should be able to see the error code which should explain the issue
please re-try this and provide the updated log if additional help is needed

**Comment by CHAUHC01** [comment]
> 

I think this should be an active issue. I'm on the right version, got the correct Azure AD app permissions/Service Principal setup, Group, Enabled Service Principals in Power BI Service. Work fine for creating pipeline, assigning a workspace to any stage, deleting pipeline, assigning users to pipeline, assigning users to a workspace. FAILS to deploy all OR selective content in a power BI pipeline to the next stage as it either returns a Status 400 Bad request OR it cannot find the artifacts to deploy.
