### ISSUE TITLE
is this being released this month?

### ISSUE THREAD

**Issue by arjunkrishna** [microsoft/powerbi-azure-pipelines-extensions#18]
as per the documentation page -  https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-bi/deployment-pipelines-azure-devops-extension , this extension will be generally available this month. Is it going to be updated in this month's release?

https://marketplace.visualstudio.com/items?itemName=ms-pbi-api.pbi-automation-tools shows in public preview.

Thanks,
Arjun

**Comment by ranbreuer** [comment]
It is now GA'd in full.
Feel free to update to latest version
