### ISSUE TITLE
Does this extension allow you to change the data source from one workspace to another ?

### ISSUE THREAD

**Issue by Cha74** [microsoft/powerbi-azure-pipelines-extensions#7]

**Comment by MahirDiab** [comment]
Hi @Cha74 , can you please elaborate what do you mean by "change the data source from one workspace to another"

do you mean [Create deployment rules](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#step-4---create-deployment-rules)?
if so then this extension doesn't support creating the rules, you can do his today only using powerbi.com
but if the rules already created then the deploy task in the extension will use the same rules.

if you mean the ability to change the dataset datasources similar to [Update Datasources In Group API](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/update-datasources-in-group), then this functionality is not supported today.

would like to hear back from you to better understand what functionality you are looking for.

**Comment by Cha74** [comment]
Hi @MahirDiab, 

Thank you for your answer. 

To be clearer : 
I would like that when I automatically deploy Power BI elements (report, dataset, dataflow ...) from a DEV workspace to a TEST workspace for example the data source on which the Power BI elements point changes to point from a DEV source to a Test source, for exemple a DEV Datamart to a TEST Datamart. 

I don't know if this is clearer ?

**Comment by MahirDiab** [comment]
@Cha74, Power BI internal dependencies, like report to dataset or dataset to dataflow will be mapped automatically.
e.g. if you have a dataset connected to a dataflow and both are on the same workspace when deployed you will have copies of these artifacts and they will be connected to each other (test dataset connected to test dataflow)

to manage connections outside of Power BI, like dataset being connected to SQL Azure we have rules.
rules can only be created using PowerBI.com you can see more on the link i provided before - [Create deployment rules](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#step-4---create-deployment-rules)
make sure to check the limitations section, supported datasources list and for other types you can use parameter rules.
all should be described on the article.

you can't create new rules using the extension, but if you have a pipeline where you have already created the rules.
when using the extension to deploy, the same rules will be used like in PowerBI.com

does it make sense? hope this answers your question.
