### ISSUE TITLE
Selective Deployment keeps calling DeployAll API

### ISSUE THREAD

**Issue by rjagdon** [microsoft/powerbi-azure-pipelines-extensions#8]
Deploy content In a Deployment Pipeline task keeps calling DeployAll API as seen on logs.

Sample configuration 
![image](https://user-images.githubusercontent.com/53030174/154038887-6684e1d9-bf45-452c-a2bc-ade1b7e1a5ac.png)

Logs and testing show it will still perform DeployAll instead of Selective - https://docs.microsoft.com/en-us/rest/api/power-bi/pipelines/selective-deploy
![image](https://user-images.githubusercontent.com/53030174/154039312-6f6c6a09-74a6-499b-b0f9-499ff54904e5.png)

**Comment by MahirDiab** [comment]
Hi @rjagdon, Thanks for reporting the issue.
following your report i have fixed the issue and deployed it to Marketplace.
the new version with the fix is 1.0.10
